AT_SETUP([pyre (?P=group) \g<group2> unknown])

dnl Create pattern file.
dnl Group (?P=bad) is not defined, so there is an RE fault.
dnl
AT_DATA([14.re], [dnl
r(?P<re>.*)ge(?P=bad)x
second
(third|3) is \2
fourth
\g<fifth>
])

dnl Create output file.
dnl
AT_DATA([14.out], [dnl
r+*gex
second
third is third
fourth
5
])

dnl Create diff re file.
dnl The ERROR line changes between python 2.6, 2.7, and 3.7.
dnl
AT_DATA([14.diffre], [dnl
# ERROR: Pattern "r\(\?P<re>\.\*\)ge\(\?P=bad\)x": unknown group name(: 'bad'| 'bad' at position 21)?
1c1
< r\(\?P<re>\.\*\)ge\(\?P=bad\)x
---
> r\+\*gex
# ERROR: Pattern "\(third\|3\) is \\2": (bogus escape: '\\\\2'|invalid group reference 2 at position 18)
3c3
< \(third\|3\) is \\2
---
> third is third
# ERROR: Pattern \g<fifth>: Unknown group
5c5
< \g<fifth>
---
> 5
])

AX_AT_DIFF_PYRE([14.re], [14.out], [1], [stdout])
AX_AT_DIFF_PYRE([14.diffre], [stdout])

AT_CHECK([diff 14.re 14.out | ${PYTHON} ${abs_top_srcdir}/src/pyrediff -f], [1], [stdout])
AX_AT_DIFF_PYRE([14.diffre], [stdout])

AT_CHECK([${PYTHON} ${abs_top_srcdir}/src/pyrediff 14.re 14.out], [1], [stdout])
AX_AT_DIFF_PYRE([14.diffre], [stdout])

AT_CLEANUP()
